### ISSUE TITLE
Repost request

### ISSUE THREAD

**Issue by LittleHed** [Orf1/Anti-Xray-Plus#1]
Hello,I am from China.I think this plugins is very good  because it helps my server.
I want to reprint this plugin to Chinese minecraft forum.May I?
I just want to share this plugin to more people.

**Comment by LittleHed** [comment]
The url of minecraft forum is www.mcbbs.net

**Comment by Orf1** [comment]
Hey, sure as long as you send them a link to the github and spigot page!
https://www.spigotmc.org/resources/anti-xray-plus.80787/
https://github.com/Orf1/Anti-Xray-Plus

**Comment by Orf1** [comment]
Also make sure to use the latest release of the plugin, I made some major fixes.

**Comment by LittleHed** [comment]
ok,I will send them the link to the spiogt page

**Comment by LittleHed** [comment]
And can I translate the language to Chinese?

**Comment by Orf1** [comment]
Sure!

**Comment by LittleHed** [comment]
And I want to give some advise to you.May you add more ore detect?If only have the detect for diamond_ore,it can't prevent players who only mine the iron_ore or other ore

**Comment by Orf1** [comment]
Yeah, hopefully I will be able to add that soon. Its just a lot of work and I am a little busy right now.
